Encrypt PKCS11 configuration appropriately
Signed-off-by: Sergio Arroutbi <sarroutb@redhat.com>

diff --git a/clevis-encrypt-pkcs11 b/clevis-encrypt-pkcs11
--- a/clevis-encrypt-pkcs11
+++ b/clevis-encrypt-pkcs11
@@ -20,6 +20,28 @@ set -eo pipefail
 
 PIN_NAME=pkcs11
 
+SUMMARY="Encrypts using a PKCS#11 token"
+
+if [ "$1" == "--summary" ]; then
+    echo "$SUMMARY"
+    exit 0
+fi
+
+if [ -t 0 ]; then
+    exec >&2
+    echo
+    echo "Usage: clevis encrypt pkcs11 CONFIG < PLAINTEXT > JWE"
+    echo
+    echo "$SUMMARY"
+    echo
+    echo "This command uses the following configuration properties:"
+    echo
+    echo "  uri: <string>   The PKCS#11 URI (REQUIRED)"
+    echo
+    exit 2
+fi
+
+
 on_exit() {
     [ -d "${CLEVIS_PKCS11}" ] || exit 0
     rm -rf "${CLEVIS_PKCS11}"
@@ -29,6 +51,11 @@ unset CLEVIS_PKCS11
 # We first check whether the configuration is a valid JSON.
 if ! cfg="$(jose fmt --json="$1" --object --output=- 2>/dev/null)" ; then
     echo 'Configuration is malformed' >&2
+    exit 1
+fi
+
+if ! uri="$(jose fmt -j- -Og uri -u- <<< "$cfg")"; then
+    echo "Missing the required PKCS#11 'uri' property!" >&2
     exit 1
 fi
 
@@ -60,8 +87,8 @@ if ! jwk_enc="$(printf '%s' "${jwk}" | openssl rsautl -encrypt -pubin \
 fi
 
 # And the JWE.
-template=$(printf '{"protected":{"clevis":{"pin":"%s","%s":{}}}}' \
-                  "${PIN_NAME}" "${PIN_NAME}")
+template=$(printf '{"protected":{"clevis":{"pin":"%s","%s":{"uri":"%s"}}}}' \
+                  "${PIN_NAME}" "${PIN_NAME}" "${uri}")
 
 # Save key.
 jwe="$(jose fmt --json="${template}" --get protected --get clevis \
