Check invalid PIN on decryption error
Signed-off-by: Sergio Arroutbi <sarroutb@redhat.com>

diff --git a/clevis-decrypt-pkcs11 b/clevis-decrypt-pkcs11
--- a/clevis-decrypt-pkcs11
+++ b/clevis-decrypt-pkcs11
@@ -108,19 +108,18 @@ if ! PIN_value="$(clevis_get_pin_value_from_uri ${uri})"; then
     PIN_value=$(cat "${PIN_FILE}" 2>/dev/null || :)
 fi
 
-if ! pkcs11-tool -pkcs11-tool --login --test -p "${PIN_value}"-login --test \
-                 -p "${PIN_value}" --module "${module_path}" \
-                 2>"${ERR}" >/dev/null; then
-    cat "${ERR}" >&2
-    echo "Invalid PIN" >&2
-    exit 1
-fi
-
 if ! jwk="$(pkcs11-tool --login --decrypt --input-file ${ENC} \
             -p ${PIN_value} --module ${module_path} 2>${ERR})" \
             || [ -z "${jwk}" ]; then
     cat "${ERR}" >&2
     echo "Unable to decrypt the JWK" >&2
+    # Check if it is an issue with PIN (to dump error appropriately)
+    if ! pkcs11-tool -pkcs11-tool --login --test -p "${PIN_value}"-login --test \
+                     -p "${PIN_value}" --module "${module_path}" \
+                     2>"${ERR}" >/dev/null; then
+        cat "${ERR}" >&2
+        echo "Invalid PIN" >&2
+    fi
     exit 1
 fi
 
