Decrypt only clevis pkcs11 sock entries (#66)
Signed-off-by: Sergio Arroutbi <sarroutb@redhat.com>

diff --git a/systemd/libexec/clevis-luks-pkcs11-askpin b/systemd/libexec/clevis-luks-pkcs11-askpin
--- a/systemd/libexec/clevis-luks-pkcs11-askpin
+++ b/systemd/libexec/clevis-luks-pkcs11-askpin
@@ -16,27 +16,29 @@ pkcs11-tool -L
 # TODO: check for clevis-pkcs11*sock
 grep -v "^#" /etc/crypttab | while read -r line;
 do
-    password_found=0
-    while [ ${password_found} -ne 1 ]; do
-        pin=$(systemd-ask-password "Please, insert PKCS11 PIN:")
-        uuid=$(echo "${line}" | awk '{print $2}')
-        noUUID=$(echo "${uuid}" | sed -e 's@UUID=@@g')
-        # Get key from PKCS11 pin here and feed AF_UNIX socket program
-        echo "${pin}" > /run/systemd/clevis-pkcs11.pin
-        if ! mapped_device=$(clevis_map_device "${uuid}"); then
-            echo "Could not check mapped device for UID:${uuid}"
-        fi
-        if ! passphrase=$(clevis_luks_unlock_device "${mapped_device}") || [ -z "${passphrase}" ]; then
-            echo "Could not unlock device:${mapped_device}"
-            continue
-        fi
-        password_found=1
-        echo "Device:${mapped_device} unlocked successfully"
-        echo "${passphrase}" > /run/systemd/clevis-pkcs11."${noUUID}".passphrase
-        # Send passphrase to control socket
-        luks_device="luks-${noUUID}"
-        # TODO: select control socket according to crypttab entry
-        echo -n "${luks_device},${passphrase}" | socat UNIX-CONNECT:/run/systemd/clevis-pkcs11.control.sock -
-        rm -f /run/systemd/clevis-pkcs11.pin
-    done
+    if echo "${line}" | grep -E "clevis-pkcs11.sock" 1>/dev/null;
+    then
+        password_found=0
+        while [ ${password_found} -ne 1 ]; do
+            uuid=$(echo "${line}" | awk '{print $2}')
+            noUUID=$(echo "${uuid}" | sed -e 's@UUID=@@g')
+            pin=$(systemd-ask-password "Please, insert PKCS11 PIN (${uuid}):")
+            # Get key from PKCS11 pin here and feed AF_UNIX socket program
+            echo "${pin}" > /run/systemd/clevis-pkcs11.pin
+            if ! mapped_device=$(clevis_map_device "${uuid}"); then
+                echo "Could not check mapped device for UID:${uuid}"
+            fi
+            if ! passphrase=$(clevis_luks_unlock_device "${mapped_device}") || [ -z "${passphrase}" ]; then
+                echo "Could not unlock device:${mapped_device}"
+                continue
+            fi
+            password_found=1
+            echo "Device:${mapped_device} unlocked successfully"
+            echo "${passphrase}" > /run/systemd/clevis-pkcs11."${noUUID}".passphrase
+            # Send passphrase to control socket
+            luks_device="luks-${noUUID}"
+            # TODO: select control socket according to crypttab entry
+            echo -n "${luks_device},${passphrase}" | socat UNIX-CONNECT:/run/systemd/clevis-pkcs11.control.sock -
+        done
+    fi
 done
